package com.brunpola.cv_management.dao.impl;

import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.jdbc.core.JdbcTemplate;

@ExtendWith(MockitoExtension.class)
public class PersonDaoImplTests {

  @Mock private JdbcTemplate jdbcTemplate;

  @InjectMocks private PersonDaoImpl underTest;

  // NOTE TO SELF: check later what changes with autogenerated ID
  // @Test
  // public void testThatCreatePersonGeneratesTheCorrectSql() {
  //   Person person = TestDataUtil.createTestPerson();

  //   underTest.create(person);

  //   verify(jdbcTemplate)
  //       .update(
  //           eq("INSERT INTO People (FirstName, LastName) VALUES (?, ?);"), eq("Bruno"),
  // eq("Pola"));
  // }

  @Test
  public void testThatFindOnePersonGeneratesTheCorrectSql() {
    underTest.findOne(1L);

    verify(jdbcTemplate)
        .query(
            eq("SELECT ID, FirstName, LastName FROM People WHERE ID = ? LIMIT 1;"),
            ArgumentMatchers.<PersonDaoImpl.PersonRowMapper>any(),
            eq(1L));
  }

  @Test
  public void testThatFindPersonGeneratesTheCorrectSql() {
    underTest.find();

    verify(jdbcTemplate)
        .query(
            eq("SELECT ID, FirstName, LastName FROM People;"),
            ArgumentMatchers.<PersonDaoImpl.PersonRowMapper>any());
  }
}
