package com.brunpola.cv_management.dao.impl;

import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.jdbc.core.JdbcTemplate;

@ExtendWith(MockitoExtension.class)
public class ProjectDaoImplTests {

  @Mock private JdbcTemplate jdbcTemplate;

  @InjectMocks private ProjectDaoImpl underTest;

  // // NOTE TO SELF: check later what changes with autogenerated ID
  // @Test
  // public void TestThatCreateProjectGeneratesTheCorrectSql() {
  //   Project project = TestDataUtil.createTestProject();

  //   underTest.create(project);

  //   verify(jdbcTemplate)
  //       .update(
  //           eq("INSERT INTO Projects (ID, ProjectName) VALUES (?, ?);"),
  //           eq(1L),
  //           eq("Mockito Testing"));
  // }

  @Test
  public void testThatFindOneProjectGeneratesTheCorrectSql() {
    underTest.findOne(1L);

    verify(jdbcTemplate)
        .query(
            eq("SELECT ID, ProjectName FROM Projects WHERE ID = ? LIMIT 1;"),
            ArgumentMatchers.<ProjectDaoImpl.ProjectRowMapper>any(),
            eq(1L));
  }
}
