package com.brunpola.cv_management.dao.impl;

import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.jdbc.core.JdbcTemplate;

@ExtendWith(MockitoExtension.class)
public class SkillDaoImplTests {

  @Mock private JdbcTemplate jdbcTemplate;

  @InjectMocks private SkillDaoImpl underTest;

  // // NOTE TO SELF: check later what changes with autogenerated ID
  // @Test
  // public void TestThatCreateSkillGeneratesTheCorrectSql() {
  //   Skill skill = createTestSkill();

  //   underTest.create(skill);

  //   verify(jdbcTemplate)
  //       .update(eq("INSERT INTO Skills (ID, SkillName) VALUES (?, ?);"), eq(1L), eq("Mockito"));
  // }

  @Test
  public void testThatFindOneSkillGeneratesTheCorrectSql() {
    underTest.findOne(1L);

    verify(jdbcTemplate)
        .query(
            eq("SELECT ID, SkillName FROM Skills WHERE ID = ? LIMIT 1;"),
            ArgumentMatchers.<SkillDaoImpl.SkillRowMapper>any(),
            eq(1L));
  }
}
